"""Add labor_cost to Recipe

Revision ID: 188fbe208dc0
Revises: 
Create Date: 2024-09-04 00:17:36.092406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188fbe208dc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labor_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('labor_cost')

    # ### end Alembic commands ###
