"""Add purchase_price to Material

Revision ID: 29ae4bb31da9
Revises: 853b4d54976e
Create Date: 2024-09-05 22:52:08.987202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ae4bb31da9'
down_revision = '853b4d54976e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
