"""Add total_cost to Recipe

Revision ID: 853b4d54976e
Revises: 188fbe208dc0
Create Date: 2024-09-04 00:29:06.272919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853b4d54976e'
down_revision = '188fbe208dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
