"""Add total_cost and cost_rate to Recipe

Revision ID: bf0be7717203
Revises: f79def97e234
Create Date: 2024-09-07 10:36:33.382914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0be7717203'
down_revision = 'f79def97e234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False, server_default="0.0"))
        batch_op.add_column(sa.Column('profit_margin', sa.Float(), nullable=False, server_default="0.0"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
