"""Add listing_price to Recipe

Revision ID: f79def97e234
Revises: 29ae4bb31da9
Create Date: 2024-09-05 23:21:09.926281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79def97e234'
down_revision = '29ae4bb31da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_price', sa.Float(), nullable=False, server_default='0.0'))  # デフォルト値0.0を追加
        batch_op.alter_column('labor_cost',
                    existing_type=sa.FLOAT(),
                    nullable=False,
                    server_default=sa.text('0.0'))

        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.FLOAT(), nullable=True))
        batch_op.alter_column('labor_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('listing_price')

    # ### end Alembic commands ###
